### ISSUE TITLE
No hay ejemplo de integración en VIM

### ISSUE THREAD

**Issue by skgsergio** [acmfi/cursogit2016-2017#1]
Todo el mundo sabe que el mejor editor es VIM por lo que debería añadirse en los ejemplos de integración.

**Comment by rockneurotiko** [comment]
Lo sentimos, pero vim no tiene una integracion tan interesante como para explicarlo.

**Comment by skgsergio** [comment]
Me parece faltal que me discrimineis https://github.com/tpope/vim-fugitive

**Comment by rockneurotiko** [comment]
Estaba en la charla, pero se fugó (killme)
